
-- create table bu_personal
 create table bu_personal (
    bu_personal_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
 bu_first_name varchar2(50),
 bu_last_name varchar(50) ,
 bu_father_name varchar(50),
 bu_birth_city varchar(80),
 bu_address varchar(120),
 bu_city varchar(50),
 bu_national_code varchar2(10) unique,
 bu_birth_certificate_no varchar2(50),
 bu_postal_code varchar(50),
 bu_meter_number varchar(50),
 bu_region varchar2(50),
 bu_crimintal_record_status char(1) check (bu_crimintal_record_status in ('Y','N')),
 bu_addiction_status number(1) check (bu_addiction_status in (1,0)),
 bu_marital_status varchar2(5) check (bu_marital_status in ('true','false')),
 bu_military_status varchar2(1) check (bu_military_status in ('Y','N')),
 bu_driving_license_status number(1) check (bu_driving_license_status in (1,0)),
 bu_created_name varchar2(50),
 bu_created_date date,
 bu_updated_name varchar2(50),
  bu_updated_date date,
  bu_birth_day date,
  bu_nationality varchar2(50) 
 );

